name: Rust

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update stable
    - name: Build Debug
      run: cargo build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: entropyscan-rs_linux_amd64_debug 
        path: target/debug/entropyscan-rs
    - name: Build Release
      run: cargo build --release
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: entropyscan-rs_linux_amd64 
        path: target/release/entropyscan-rs
  
  build_mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update stable
    - name: Build Debug
      run: cargo build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: entropyscan-rs_darwin_amd64_debug 
        path: target/debug/entropyscan-rs
    - name: Build Release
      run: cargo build --release --target x86_64-apple-darwin
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: entropyscan-rs_darwin_amd64 
        path: target/x86_64-apple-darwin/release/entropyscan-rs
      
  build_windows:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Update Rust
      run: rustup update stable
    - name: Install MingW
      run: sudo apt install -y mingw-w64
    - name: Add Windows Triple
      run: rustup target add x86_64-pc-windows-gnu 
    - name: Build Debug
      run: cargo build --target x86_64-pc-windows-gnu
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: entropyscan-rs_win_64_debug.exe
        path: target/x86_64-pc-windows-gnu/debug/entropyscan-rs.exe
    - name: Build Release
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: entropyscan-rs_win_64.exe
        path: target/x86_64-pc-windows-gnu/release/entropyscan-rs.exe
